// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu6DjgGen1ClmAnFqH8hDbwUbex3RW57g',
    appId: '1:850647467382:web:bf5a96e899c6234070a657',
    messagingSenderId: '850647467382',
    projectId: 'resourceful-369d3',
    authDomain: 'resourceful-369d3.firebaseapp.com',
    databaseURL: 'https://resourceful-369d3-default-rtdb.firebaseio.com',
    storageBucket: 'resourceful-369d3.appspot.com',
    measurementId: 'G-TPMSZY8KXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLNBzBaCt1hq6Rgk_3FkNJaUM6Ek7l3cg',
    appId: '1:850647467382:android:d56dc621cbe255cb70a657',
    messagingSenderId: '850647467382',
    projectId: 'resourceful-369d3',
    databaseURL: 'https://resourceful-369d3-default-rtdb.firebaseio.com',
    storageBucket: 'resourceful-369d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY0UwsQ7hdnbdm3gKG_cljtkTJpHcHdp4',
    appId: '1:850647467382:ios:150a860ef390b1e470a657',
    messagingSenderId: '850647467382',
    projectId: 'resourceful-369d3',
    databaseURL: 'https://resourceful-369d3-default-rtdb.firebaseio.com',
    storageBucket: 'resourceful-369d3.appspot.com',
    iosClientId:
        '850647467382-p51g8gs9h87mtj5cbe8mf9caia3tte06.apps.googleusercontent.com',
    iosBundleId: 'com.example.resourceful',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY0UwsQ7hdnbdm3gKG_cljtkTJpHcHdp4',
    appId: '1:850647467382:ios:150a860ef390b1e470a657',
    messagingSenderId: '850647467382',
    projectId: 'resourceful-369d3',
    databaseURL: 'https://resourceful-369d3-default-rtdb.firebaseio.com',
    storageBucket: 'resourceful-369d3.appspot.com',
    iosClientId:
        '850647467382-p51g8gs9h87mtj5cbe8mf9caia3tte06.apps.googleusercontent.com',
    iosBundleId: 'com.example.resourceful',
  );
}
